# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20190304_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bicicleta',
        ),
    ]
