# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_bicicleta_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disco',
        ),
    ]
